version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  book-flight-module:
    image: vikrantdocker9/vicky-selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=book-flight-module.xml
    volumes:
      - ./Result/book-flight:/usr/share/udemy/test-output